import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import placesData from "../data/places.json";
import styles from "../styles/Home.module.css";
import { GoogleMap, useLoadScript, Marker } from "@react-google-maps/api";

export default function Home(): JSX.Element {
  const [latLang, setLatLang] = useState({
    lat: 30.279728880333206,
    lng: -97.67472504604278,
  });
  const containerStyle = {
    width: "400px",
    height: "400px",
  };

  const { push } = useRouter();

  const mapStuff = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  });

  const getLatLangFromAddress = async (address: string) => {
    const response = await fetch(
      `https://maps.googleapis.com/maps/api/geocode/json?address=$${address}&key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}`
    );
    const responseJSON = await response.json();
    setLatLang(responseJSON.results[0].geometry.location);
  };

  useEffect(() => {
    const addressParam = "?address=2713 E 2nd St, Austin, TX 78702";
    console.log("addressParam", addressParam);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {Object.keys(placesData).map((key) => {
            console.log("hey?", key, placesData);
            const place = placesData[key];
            return (
              <li>
                <div
                  className={styles.place}
                  onClick={() => push(`/places/${key}`)}
                >
                  <h4>{place.name}</h4>
                  <p>{place.genre}</p>
                  <div>
                    <p>{place.price}</p>
                  </div>
                </div>
                <a href={place.url} target="_none">
                  website
                </a>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
